import { NavLink } from "./generals";

export const navLinks: NavLink[] = [
  { href: "#home", label: "Home" },
  { href: "#about-me", label: "About" },
  { href: "#projects", label: "Projects" },
  { href: "#contact-me", label: "Contact" },
];

export const skillList = [
  "React",
  "Node",
  "Mongodb",
  "Express",
  "Next",
  "Javascript",
  "Socket",
  "CSS",
  "Bootstrap",
  "tailwind",
  "MUI",
  "Typescript",
  "nestjs",
  "mysql",
  "firebase",
  "monorepo",
  "Payment Gateways",
  "Docker",
  "CI/CD",
  "AWS ( EC2/Serverless )",
  "Graphql",
  "Git",
  "threejs",
  "React Native",
  "R&D",
  "Data Structure and Algorithms",
  "State Managment",
  "Problem Solving",
  "leadership",
  "Client Handling",
];

export const internSkillList = [
  "React",
  "Node",
  "Mongodb",
  "CSS",
  "Express",
  "Laravel",
  "Fundamentals of Web Development",
];
export const coFounderSkillList = [
  "React",
  "Node",
  "Mongodb",
  "CSS",
  "Express",
  "AWS",
  "Paytm",
];
export const tySkillList = [
  "MERN",
  "R&D",
  "Communication",
  "Project Managment",
  "Leadership",
  "Client Handling",
];

export const projectList = [
  {
    name: "RealEstatePro360",
    github: "",
    thumbnail: "real-estate.jpg",
    des: "A B2B SaaS platform, employers to create dynamic PDF layouts and forms. Employees generate detailed PDF reports with CAD integration and 2D/3D visualizations using SVG.",
    stack: [
      { link: "stack/react.svg", alt: "react" },
      { link: "stack/node.svg", alt: "node" },
      { link: "stack/ex.svg", alt: "express" },
      { link: "stack/mongo.svg", alt: "mongodb" },
      { link: "stack/js.svg", alt: "js" },
      { link: "stack/aws.svg", alt: "aws" },
      { link: "stack/threejs.svg", alt: "threejs" },
      { link: "stack/pdf.png", alt: "pdf" },
      { link: "stack/arcsite.jpeg", alt: "arcsite" },
    ],
    tags: ["CAD", "Real Estate"],
    link: "https://gkcodes.wordpress.com/2024/01/30/realestatepro360/",
  },
  {
    name: "PerformancePilot",
    github: "",
    thumbnail: "resturant.jpg",
    des: "Productivity B2B SaaS for onboarding and performance tracking By leveraging Point Allocation Algorithm and External APIs, fueling healthy competition and driving better results.",
    stack: [
      { link: "stack/react.svg", alt: "react" },
      { link: "stack/node.svg", alt: "node" },
      { link: "stack/ex.svg", alt: "express" },
      { link: "stack/mongo.svg", alt: "mongodb" },
      { link: "stack/js.svg", alt: "js" },
      { link: "stack/aws.svg", alt: "aws" },
      { link: "stack/stripe.svg", alt: "stripe" },
    ],
    tags: ["Resturents"],
    link: "https://gkcodes.wordpress.com/2024/01/30/performancepilot/",
  },
  {
    name: "CrossPay",
    github: "",
    thumbnail: "payment.avif",
    des: "Cross-border Secure Payment app, blending blockchain efficiency with traditional gateways. Experience swift, secure, and low-cost money transfers globally, Seamless way to support your family and friends.",
    stack: [
      { link: "stack/ios.png", alt: "ios" },
      { link: "stack/node.svg", alt: "node" },
      { link: "stack/ex.svg", alt: "express" },
      { link: "stack/mongo.svg", alt: "mongodb" },
      { link: "stack/js.svg", alt: "js" },
      { link: "stack/aws.svg", alt: "aws" },
      { link: "stack/sila.jpeg", alt: "silamoney" },
      { link: "stack/flutterwave.png", alt: "flutterwave" },
    ],
    tags: ["Fintech"],
    link: "https://gkcodes.wordpress.com/2024/01/30/crosspay/",
  },
  {
    name: "CodeSandBox-lite",
    github: "https://github.com/Keyur-Gondaliya/codedamn-lite",
    thumbnail: "codesandbox-lite.png",
    des: "Cloud base Sandbox environment for various frameworks and languages powered by Docker Containers. ",
    stack: [
      { link: "stack/next.svg", alt: "next" },
      { link: "stack/node.svg", alt: "node" },
      { link: "stack/ex.svg", alt: "express" },
      { link: "stack/mongo.svg", alt: "mongodb" },
      { link: "stack/ts.svg", alt: "ts" },
      { link: "stack/aws.svg", alt: "aws" },
      { link: "stack/docker.png", alt: "docker" },
    ],
    tags: ["Software Development"],
    link: "https://gkcodes.wordpress.com/2024/05/20/codesandbox-lite/",
  },
  {
    name: "DuoSync-Call",
    github: "https://github.com/Keyur-Gondaliya/DuoSync-Call",
    thumbnail: "vc-ac.avif",
    des: "WebRTC based platform for instant and secure one-to-one video and audio calls directly through web browsers, ensuring a seamless real-time communication experience without additional plugins.",
    stack: [
      { link: "stack/next.svg", alt: "next" },
      { link: "stack/node.svg", alt: "node" },
      { link: "stack/ex.svg", alt: "express" },
      { link: "stack/mongo.svg", alt: "mongodb" },
      { link: "stack/ts.svg", alt: "ts" },
      { link: "stack/aws.svg", alt: "aws" },
      { link: "stack/vercel.svg", alt: "vercel" },
      { link: "stack/webrtc.png", alt: "webrtc" },
    ],
    tags: ["CommunicationTechnology"],
    link: "https://gkcodes.wordpress.com/2024/01/30/duosync-call/",
  },
  {
    name: "Resume Builder",
    github: "https://github.com/Keyur-Gondaliya/Resume-Builder",
    thumbnail: "resume1.jpg",
    des: "Introducing our innovative SaaS platform that streamlines resume creation. Choose from stunning layouts, input your details effortlessly, and generate a polished PDF resume instantly.",
    stack: [
      { link: "stack/react.svg", alt: "react" },
      { link: "stack/node.svg", alt: "node" },
      { link: "stack/ex.svg", alt: "express" },
      { link: "stack/mongo.svg", alt: "mongodb" },
      { link: "stack/ts.svg", alt: "ts" },
      { link: "stack/aws.svg", alt: "aws" },
      { link: "stack/pdf.png", alt: "pdf" },
    ],
    tags: ["Career Services"],
    link: "https://gkcodes.wordpress.com/2024/01/30/resume-builder/",
  },
  {
    name: "DataMagnet",
    github: "https://github.com/Keyur-Gondaliya/kiama-client",
    thumbnail: "data-sell.jpg",
    des: "It's a cutting-edge industrial information hub. Empower users with precision through dynamic data filtration, optimizing both frontend and backend for seamless insights and invaluable decision-making in real-time.",
    stack: [
      { link: "stack/react.svg", alt: "react" },
      { link: "stack/node.svg", alt: "node" },
      { link: "stack/ex.svg", alt: "express" },
      { link: "stack/mongo.svg", alt: "mongodb" },
      { link: "stack/js.svg", alt: "js" },
      { link: "stack/aws.svg", alt: "aws" },
      { link: "stack/threejs.svg", alt: "threejs" },
    ],
    tags: ["Industrial"],
    link: "https://gkcodes.wordpress.com/2024/01/30/datamagnet/",
  },
  {
    name: "FlexiSync Inventory",
    github: "",
    thumbnail: "inventory.avif",
    des: "Beautiful Platform designed for seamless product, purchase, and sales management. This innovative system allows getting dynamic data from users by creating forms through APIs.",
    stack: [
      { link: "stack/react.svg", alt: "react" },
      { link: "stack/js.svg", alt: "js" },
    ],
    tags: ["Inventory"],
    link: "https://gkcodes.wordpress.com/2024/01/30/flexisync-inventory/",
  },
  {
    name: "ChefSync Pro",
    github: "",
    thumbnail: "chef.jpg",
    des: "ChefSync Pro is the ultimate SAAS platform empowering chefs to effortlessly manage schedules, showcase menus, and streamline payments, fostering growth and efficiency in their personal culinary businesses.",
    stack: [
      { link: "stack/react.svg", alt: "react" },
      { link: "stack/node.svg", alt: "node" },
      { link: "stack/ex.svg", alt: "express" },
      { link: "stack/mongo.svg", alt: "mongodb" },
      { link: "stack/js.svg", alt: "js" },
      { link: "stack/aws.svg", alt: "aws" },
      { link: "stack/stripe.svg", alt: "stripe" },
    ],
    tags: ["Career Services"],
    link: "https://gkcodes.wordpress.com/2024/01/30/chefsync-pro/",
  },
  {
    name: "PolySnap PDF",
    github: "",
    thumbnail: "ea1.jpg",
    des: "Cutting-edge Platform that empowers users to effortlessly capture, customize, and manipulate specific areas of PDFs and perform operation on geometry shapes effortlessly.",
    stack: [
      { link: "stack/react.svg", alt: "react" },
      { link: "stack/js.svg", alt: "js" },
    ],
    tags: ["SVG", "Geometry", "pdf"],
    link: "https://gkcodes.wordpress.com/2024/01/30/polysnap-pdf/",
  },
  {
    name: "NPM-3D-Sun",
    github: "https://github.com/Keyur-Gondaliya/npm-3D-sun",
    thumbnail: "3d.png",
    des: "Revolutionize celestial exploration with our Three.js-powered npm package. Immerse yourself in a 3D sun, surrounded by stars. Zoom and rotate for a personalized journey through the cosmos.",
    stack: [
      { link: "stack/react.svg", alt: "react" },
      { link: "stack/ts.svg", alt: "ts" },
      { link: "stack/threejs.svg", alt: "threejs" },
    ],
    tags: ["npm"],
    link: "https://www.npmjs.com/package/@keyur-gondaliya/3d-sun",
  },
  {
    name: "Nike-Branding",
    github: "https://github.com/Keyur-Gondaliya/Nike-Branding",
    thumbnail: "nike.png",
    des: "Build a beautiful Nike landing page for enhanced user experience and marketing prowess, representing the digital presence of any organization for better bussiness growth.",
    stack: [
      { link: "stack/react.svg", alt: "react" },
      { link: "stack/ts.svg", alt: "ts" },
      { link: "stack/tailwind.png", alt: "tailwind" },
    ],
    tags: ["LandingPage", "selfLearning"],
    link: "https://gkcodes.wordpress.com/2024/01/30/nike-branding/",
  },
  {
    name: "Admin Analytics",
    github: "",
    thumbnail: "admin.webp",
    des: "Crafted a seamless admin panel with an intuitive dashboard, empowering efficient management of users, houses, products, and CMS. Elevate control with insightful analytics for informed decision-making.",
    stack: [
      { link: "stack/react.svg", alt: "react" },
      { link: "stack/node.svg", alt: "node" },
      { link: "stack/ex.svg", alt: "express" },
      { link: "stack/mongo.svg", alt: "mongodb" },
      { link: "stack/js.svg", alt: "js" },
      { link: "stack/aws.svg", alt: "aws" },
    ],
    tags: ["Admins"],
    link: "https://gkcodes.wordpress.com/2024/01/30/admin-analytics/",
  },
  {
    name: "Quiz Master",
    github: "https://github.com/Vzila/Q-master/tree/master",
    thumbnail: "e-learning.jpg",
    des: "Create quizzes, assign topics, and assess student performance. Receive detailed insights on individual and class weaknesses, empowering teachers to enhance targeted instruction for improved learning outcomes.",
    stack: [
      { link: "stack/react.svg", alt: "react" },
      { link: "stack/node.svg", alt: "node" },
      { link: "stack/ex.svg", alt: "express" },
      { link: "stack/mongo.svg", alt: "mongodb" },
      { link: "stack/js.svg", alt: "js" },
    ],
    tags: ["E-Education"],
    link: "https://wordpress.com/post/gkcodes.wordpress.com/305",
  },
  {
    name: "Electricity Billing System",
    github:
      "https://github.com/Vzila/Electricity_Billing_System/tree/main/electricity-managment-main",
    thumbnail: "ebs.png",
    des: "EBS is an advanced Electricity Billing System SAAS that empowers both employees to efficiently generate bills and normal users to effortlessly manage and pay their electricity bills with ease",
    stack: [
      { link: "stack/react.svg", alt: "react" },
      { link: "stack/node.svg", alt: "node" },
      { link: "stack/ex.svg", alt: "express" },
      { link: "stack/js.svg", alt: "js" },
      { link: "stack/json.webp", alt: "json" },
    ],
    tags: ["Industry"],
    link: "https://wordpress.com/post/gkcodes.wordpress.com/190",
  },
  {
    name: "Resturant Reservation",
    github: "https://github.com/Vzila/Resturant-Reservation-System/tree/master",
    thumbnail: "rrs.jpg",
    des: "Hybrid App for reservation of specific table in restaurant, user-friendly interface, secure login, slot booking, menu exploration, and profile management for a personalized dining experience in the era of remote work.",
    stack: [
      { link: "stack/rn.png", alt: "reactNative" },
      { link: "stack/firebase.png", alt: "firebase" },
      { link: "stack/js.svg", alt: "js" },
    ],
    tags: ["Resturant"],
    link: "https://wordpress.com/post/gkcodes.wordpress.com/270",
  },
  {
    name: "Timetable Maker",
    github: "https://github.com/Vzila/Time-Table-generator",
    thumbnail: "ttgs.png",
    des: "Revolutionize scheduling with our Java-based SAAS Timetable Maker effortlessly create, manage, and share automated timetables, empowering faculties and students for seamless academic planning.",
    stack: [
      { link: "stack/java.webp", alt: "png" },
      { link: "stack/excel.jpeg", alt: "excel" },
    ],
    tags: ["Scheduler"],
    link: "https://wordpress.com/post/gkcodes.wordpress.com/183",
  },
  {
    name: "Data Hiding",
    github: "https://github.com/Vzila/Data-hiding-using-stegnography-",
    thumbnail: "stegnography.jpg",
    des: "Steganography as a Service ensures covert data hiding in images, preserving confidentiality.it embeds information within images, enhancing security through discreet communication channels.",
    stack: [{ link: "stack/python.png", alt: "python" }],
    tags: ["dataHiding"],
    link: "https://gkcodes.wordpress.com/2024/01/30/data-hiding-steganography/",
  },
  {
    name: "Botman",
    github: "",
    thumbnail: "botman.png",
    des: "SAAS bot delivers seamless, scalable solutions. Streamline operations, enhance user experiences, and unlock new possibilities with this cutting-edge, versatile software-as-a-service platform.",
    stack: [
      { link: "stack/react.svg", alt: "laravel" },
      { link: "stack/node.svg", alt: "php" },
    ],
    tags: ["Bot"],
    link: "https://wordpress.com/post/gkcodes.wordpress.com/229",
  },
];

export const blogList = [
  {
    link: "https://gkcodes.wordpress.com/2024/01/29/scrum-vs-agile-vs-tdd/",
    name: "Scrum vs Agile vs TDD",
    time: 2,
    des: "Scrum orchestrates, Agile adapts, TDD fortifies—Unleash Agile Mastery!",
    date: "Jan 01, 2024",
  },
  {
    link: "https://gkcodes.wordpress.com/2024/01/30/containerization/",
    name: "Containerization (Docker + k8s)",
    time: 4,
    des: "Elfficiency sealed, innovation unleashed, boundaries shattered.",
    date: "Jan 01, 2024",
  },
  {
    link: "https://gkcodes.wordpress.com/2024/01/30/react-app-performance-optimization/",
    name: "React App Performance Optimization",
    time: 4,
    des: "React to excellence: Optimize speed, elevate performance, captivate users.",
    date: "Jan 01, 2024",
  },
  {
    link: "https://gkcodes.wordpress.com/2024/01/30/reconciliation/",
    name: "Reconciliation in React DOM",
    time: 2,
    des: "Harmony in Diversity, Unity in Differences: Embrace the Power of Reconciliation",
    date: "Jan 01, 2024",
  },
];
