import { NavLink } from "./generals";

export const navLinks: NavLink[] = [
  { href: "#home", label: "Home" },
  { href: "#about-me", label: "About" },
  { href: "#projects", label: "Projects" },
  { href: "#contact-me", label: "Contact" },
];

export const projectList = [
  {
    name: "RealEstatePro360",
    github: "",
    thumbnail: "real-estate.jpg",
    des: "A B2B SaaS platform, employers to create dynamic PDF layouts and forms. Employees generate detailed PDF reports with CAD integration and 2D/3D visualizations using SVG.",
    stack: [
      { link: "stack/react.svg", alt: "react" },
      { link: "stack/node.svg", alt: "node" },
      { link: "stack/ex.svg", alt: "express" },
      { link: "stack/mongo.svg", alt: "mongodb" },
      { link: "stack/js.svg", alt: "js" },
      { link: "stack/aws.svg", alt: "aws" },
      { link: "stack/threejs.svg", alt: "threejs" },
      { link: "stack/pdf.png", alt: "pdf" },
      { link: "stack/arcsite.jpeg", alt: "arcsite" },
    ],
    tags: ["CAD", "Real Estate"],
  },
  {
    name: "PerformancePilot",
    github: "",
    thumbnail: "resturant.jpg",
    des: "Productivity B2B SaaS for onboarding and performance tracking By leveraging Point Allocation Algorithm and External APIs, fueling healthy competition and driving better results.",
    stack: [
      { link: "stack/react.svg", alt: "react" },
      { link: "stack/node.svg", alt: "node" },
      { link: "stack/ex.svg", alt: "express" },
      { link: "stack/mongo.svg", alt: "mongodb" },
      { link: "stack/js.svg", alt: "js" },
      { link: "stack/aws.svg", alt: "aws" },
      { link: "stack/stripe.svg", alt: "stripe" },
    ],
    tags: ["Resturents"],
  },
  {
    name: "CrossPay",
    github: "",
    thumbnail: "payment.avif",
    des: "Cross-border Secure Payment app, blending blockchain efficiency with traditional gateways. Experience swift, secure, and low-cost money transfers globally, Seamless way to support your family and friends.",
    stack: [
      { link: "stack/ios.png", alt: "ios" },
      { link: "stack/node.svg", alt: "node" },
      { link: "stack/ex.svg", alt: "express" },
      { link: "stack/mongo.svg", alt: "mongodb" },
      { link: "stack/js.svg", alt: "js" },
      { link: "stack/aws.svg", alt: "aws" },
      { link: "stack/sila.jpeg", alt: "silamoney" },
      { link: "stack/flutterwave.png", alt: "flutterwave" },
    ],
    tags: ["Fintech"],
  },

  {
    name: "DuoSync-Call",
    github: "https://github.com/Keyur-Gondaliya/DuoSync-Call",
    thumbnail: "vc-ac.avif",
    des: "WebRTC based platform for instant and secure one-to-one video and audio calls directly through web browsers, ensuring a seamless real-time communication experience without additional plugins.",
    stack: [
      { link: "stack/next.svg", alt: "next" },
      { link: "stack/node.svg", alt: "node" },
      { link: "stack/ex.svg", alt: "express" },
      { link: "stack/mongo.svg", alt: "mongodb" },
      { link: "stack/ts.svg", alt: "ts" },
      { link: "stack/aws.svg", alt: "aws" },
      { link: "stack/vercel.svg", alt: "vercel" },
      { link: "stack/webrtc.png", alt: "webrtc" },
    ],
    tags: ["CommunicationTechnology"],
  },
  {
    name: "Resume Builder",
    github: "https://github.com/Keyur-Gondaliya/Resume-Builder",
    thumbnail: "resume1.jpg",
    des: "Introducing our innovative SaaS platform that streamlines resume creation. Choose from stunning layouts, input your details effortlessly, and generate a polished PDF resume instantly.",
    stack: [
      { link: "stack/react.svg", alt: "react" },
      { link: "stack/node.svg", alt: "node" },
      { link: "stack/ex.svg", alt: "express" },
      { link: "stack/mongo.svg", alt: "mongodb" },
      { link: "stack/ts.svg", alt: "ts" },
      { link: "stack/aws.svg", alt: "aws" },
      { link: "stack/pdf.png", alt: "pdf" },
    ],
    tags: ["Career Services"],
  },
  {
    name: "DataMagnet",
    github: "https://github.com/Keyur-Gondaliya/kiama-client",
    thumbnail: "data-sell.jpg",
    des: "It's a cutting-edge industrial information hub. Empower users with precision through dynamic data filtration, optimizing both frontend and backend for seamless insights and invaluable decision-making in real-time.",
    stack: [
      { link: "stack/react.svg", alt: "react" },
      { link: "stack/node.svg", alt: "node" },
      { link: "stack/ex.svg", alt: "express" },
      { link: "stack/mongo.svg", alt: "mongodb" },
      { link: "stack/js.svg", alt: "js" },
      { link: "stack/aws.svg", alt: "aws" },
      { link: "stack/threejs.svg", alt: "threejs" },
    ],
    tags: ["Industrial"],
  },
];

export const skillList = [
  "React",
  "Node",
  "Mongodb",
  "Express",
  "Next",
  "Javascript",
  "Socket",
  "CSS",
  "Bootstrap",
  "tailwind",
  "MUI",
  "Typescript",
  "mysql",
  "firebase",
  "monorepo",
  "Payment Gateways",
  "Docker",
  "CI/CD",
  "AWS ( EC2/Serverless )",
  "Graphql",
  "Git",
  "threejs",
  "React Native",
  "R&D",
  "Data Structure and Algorithms",
  "State Managment",
  "Problem Solving",
  "leadership",
  "Client Handling",
];

export const internSkillList = [
  "React",
  "Node",
  "Mongodb",
  "CSS",
  "Express",
  "Laravel",
  "Fundamentals of Web Development",
];

export const tySkillList = [
  "MERN",
  "R&D",
  "Communication",
  "Project Managment",
  "Leadership",
  "Client Handling",
];
